name: 03 challenge

on: [push]

env:
    ARTIFICATE_NAME: myartificate

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: create file to save as artificate
              run: touch test.out

            - name: Upload File
              uses: actions/upload-artifact@v4.0.0
              with:
                name: file
                path: test.out

            - name: Upload Artifact
              uses: actions/upload-artifact@v4.0.0
              with:
                name: ${{env.ARTIFICATE_NAME}}
                path: .

            
